# src/data_utils.py

import random

def split_train_val(full_data, train_ratio=0.8):
    """
    Splits the data into train and validation sets based on train_ratio.
    Returns train_data, val_data.
    """
    random.shuffle(full_data)  # shuffle in place
    split_index = int(len(full_data) * train_ratio)
    train_data = full_data[:split_index]
    val_data = full_data[split_index:]
    return train_data, val_data

def split_data_3way(full_data, train_ratio=0.7, val_ratio=0.15):
    """
    Splits the data into train/val/test sets based on the given ratios.
    e.g. train_ratio=0.7, val_ratio=0.15 => test_ratio=0.15
    """
    random.shuffle(full_data)
    total = len(full_data)
    train_size = int(total * train_ratio)
    val_size = int(total * val_ratio)

    train_data = full_data[:train_size]
    val_data = full_data[train_size : train_size + val_size]
    test_data = full_data[train_size + val_size :]

    return train_data, val_data, test_data

def batch_iter(data, batch_size=8):
    """
    Simple generator that yields data in batches.
    """
    for i in range(0, len(data), batch_size):
        yield data[i : i + batch_size]


classification_data = [

    # SPORTS (label 0)
    ("The soccer team won the championship.", 0),
    ("He scored three goals in the hockey match last night.", 0),
    ("Fans celebrated the baseball victory downtown.", 0),
    ("The star quarterback announced his retirement.", 0),
    ("Tennis finals attracted record attendance this year.", 0),
    ("Basketball season is in full swing with intense rivalries.", 0),
    ("The marathon runner set a new personal best.", 0),
    ("Local swimmers broke multiple records at the meet.", 0),
    ("A new coach is transforming the team's strategy.", 0),
    ("The stadium renovation promises better facilities for spectators.", 0),
    ("A thrilling penalty shootout decided the final match.", 0),
    ("Cricket fans enjoyed a five-day test match that ended in a draw.", 0),
    ("The champion boxer defended his title successfully.", 0),
    ("Winter sports enthusiasts welcomed the fresh snowfall for skiing.", 0),
    ("Gymnasts showcased their skills at the national competition.", 0),
    ("Skateboarding is set to debut in the upcoming sports event.", 0),
    ("Volleyball teams competed in a charity tournament.", 0),
    ("Chess is often considered both a sport and a mind game.", 0),
    ("The cycling tour extended across three countries.", 0),
    ("Fans eagerly await the start of the new football season.", 0),
    ("An underdog team upset the top seed in the basketball playoffs.", 0),
    ("The sprinter shaved half a second off her personal best record.", 0),
    ("Rugby fans packed the stadium to cheer on their national squad.", 0),
    ("Sailing competitions drew international participants this summer.", 0),
    ("The new striker already has five goals this season.", 0),
    ("After a hiatus, the famous marathon returned to city streets.", 0),
    ("Athletes took precautions during extreme heat at the tennis open.", 0),
    ("The local hockey league introduced new fair-play rules.", 0),
    ("Rowing teams battled harsh winds at the regatta finals.", 0),
    ("A knockout punch ended the boxing match in the second round.", 0),
    ("Fans eagerly watched a cliffhanger finish in the motocross race.", 0),
    ("Youth teams traveled abroad for an international soccer camp.", 0),
    ("A star gymnast announced her retirement after winning gold.", 0),
    ("The swim team overcame injuries to claim the regional title.", 0),
    ("Scouts are searching for new talent at the junior baseball events.", 0),
    ("A figure skater landed a record-breaking quadruple jump.", 0),
    ("Volunteers organized a charity 5K to support school athletics.", 0),
    ("A new motorsport track opened to boost local tourism.", 0),
    ("College basketball rivalries always draw large crowds.", 0),
    ("Beach volleyball tournaments flourished during the sunny season.", 0),
    ("A promising rookie pitcher earned his first major league start.", 0),
    ("Skiers rejoiced as fresh powder blanketed the slopes.", 0),
    ("Cyclists embarked on a cross-country ride for charity.", 0),
    ("A power outage delayed the start of the night football game.", 0),
    ("Local archery clubs merged to form a stronger league.", 0),
    ("Professional golfers dealt with heavy winds at the open championship.", 0),
    ("A sports documentary premiered, highlighting extreme mountain climbing.", 0),
    ("The city built new public tennis courts to encourage youth participation.", 0),
    ("A controversial referee call sparked debates among fans.", 0),
    ("Boxers faced a grueling training camp ahead of the title bout.", 0),
    ("The new sports channel offers live coverage of lesser-known disciplines.", 0),
    ("Squash tournaments gained popularity due to recent media coverage.", 0),
    ("High school teams competed in a national cheerleading championship.", 0),
    ("A record crowd attended the final match of the indoor soccer league.", 0),
    ("Sponsorship deals brought more funding to women’s professional leagues.", 0),
    ("A lightning storm forced officials to pause the cricket match.", 0),
    ("Rowers overcame choppy waters to secure a narrow victory.", 0),
    ("The athlete credited mindfulness practices for improved performance.", 0),
    ("A new climbing wall facility attracts both novices and experts.", 0),
    ("Marathoners tested a cutting-edge hydration system during the race.", 0),

    # -------------------
    # BUSINESS (label 1)
    ("Stock markets rallied after the company's quarterly earnings report.", 1),
    ("A major merger shook up the telecommunications industry.", 1),
    ("Entrepreneurs pitched their startups to venture capitalists.", 1),
    ("The retail giant announced plans to open 50 new stores.", 1),
    ("A local bakery gained fame for its eco-friendly packaging.", 1),
    ("Business analysts predict strong consumer spending this holiday.", 1),
    ("A new CEO aims to restructure the organization for growth.", 1),
    ("Corporate taxes are expected to rise next fiscal year.", 1),
    ("Many small businesses struggle with online competition.", 1),
    ("Trade negotiations boosted export opportunities for local factories.", 1),
    ("Franchise owners expanded their restaurant chain globally.", 1),
    ("The financial sector braces for regulatory changes.", 1),
    ("A bank introduced digital tools for remote account management.", 1),
    ("E-commerce sales soared during the sale event.", 1),
    ("A major airline reported record-breaking quarterly profits.", 1),
    ("The new marketing campaign increased brand recognition significantly.", 1),
    ("Investors are watching the cryptocurrency market closely.", 1),
    ("The auto industry saw a rise in electric vehicle sales.", 1),
    ("Retail competition intensified as new players entered the market.", 1),
    ("The software startup plans to file for an IPO next year.", 1),
    ("A global shipping firm invested heavily in drone delivery technology.", 1),
    ("Local merchants banded together to launch a holiday sale campaign.", 1),
    ("The startup pivoted to a subscription model for steady revenue.", 1),
    ("An online marketplace introduced a feature for small handmade shops.", 1),
    ("A farmland investment fund soared after grain prices rose.", 1),
    ("Corporate headquarters relocated to reduce operating costs.", 1),
    ("Private equity firms competed to acquire a software giant.", 1),
    ("Franchise expansions created job opportunities in multiple regions.", 1),
    ("A foreign investor injected capital into local manufacturing plants.", 1),
    ("Several companies formed a consortium to share logistics resources.", 1),
    ("Economic forecasts predict slower growth for the luxury goods sector.", 1),
    ("An app-based service aimed to disrupt the car rental industry.", 1),
    ("Executives discussed new tariff regulations affecting supply chains.", 1),
    ("A nonprofit provided microloans to rural entrepreneurs.", 1),
    ("A record IPO signaled strong investor confidence in fintech startups.", 1),
    ("Business schools reported a surge in demand for e-commerce courses.", 1),
    ("The board approved a buyback plan to stabilize share prices.", 1),
    ("Influencer marketing agencies gained traction with global brands.", 1),
    ("An eco-friendly packaging company won a major retail contract.", 1),
    ("Staff cuts at a major corporation sparked public backlash.", 1),
    ("A boutique consultancy expanded into the Middle East market.", 1),
    ("Union negotiations led to improved benefits at the automotive plant.", 1),
    ("A new rideshare competitor undercuts rivals with lower fees.", 1),
    ("A business incubator showcased dozens of cutting-edge tech ventures.", 1),
    ("Reports show record profits for streaming service companies.", 1),
    ("A clothing brand pivoted to sustainable materials after public demand.", 1),
    ("Economic analysts warned of a possible slowdown in consumer spending.", 1),
    ("Warehouse robotics firms see exponential growth amid labor shortages.", 1),
    ("A multimillion-dollar investment revived a historic brewery district.", 1),
    ("Foreign currency fluctuations affected multinational retailers’ revenue.", 1),
    ("A major airline introduced biometric check-ins to reduce wait times.", 1),
    ("Experts predict a wave of consolidations in the food delivery sector.", 1),
    ("Businesses are adopting crypto payments to appeal to tech-savvy customers.", 1),
    ("A real estate firm launched a coworking venture in urban areas.", 1),
    ("Corporate leaders emphasized the importance of mental health initiatives.", 1),
    ("A digital bank uses AI to personalize financial advice for clients.", 1),
    ("Local shops collaborate on a shared online storefront for convenience.", 1),
    ("The tech meltdown forced some businesses to rethink future investments.", 1),
    ("The Chamber of Commerce hosted a summit to boost female entrepreneurship.", 1),
    ("A cloud-computing deal consolidated IT resources for global offices.", 1),

    # --------------------
    # ENTERTAINMENT (label 2)
    ("A blockbuster movie broke all box office records over the weekend.", 2),
    ("The pop star released a surprise album to critical acclaim.", 2),
    ("Actors gathered at the festival to premiere their new films.", 2),
    ("A hit TV series has fans debating the season finale.", 2),
    ("The rock band's reunion tour sold out in minutes.", 2),
    ("Organizers announced the lineup for the annual music festival.", 2),
    ("The award ceremony honored both veterans and new talents.", 2),
    ("A streaming service picked up a canceled show to produce new seasons.", 2),
    ("The comedian's stand-up special generated viral social media clips.", 2),
    ("A Broadway revival drew enthusiastic reviews from theater critics.", 2),
    ("Dancers performed an avant-garde routine for a modern art event.", 2),
    ("A documentary captured the lives of street performers.", 2),
    ("The sequel to a popular franchise disappointed many fans.", 2),
    ("A famous director teased his next big project at the convention.", 2),
    ("The new reality show topped the ratings chart.", 2),
    ("An indie film gained international acclaim for its unique storytelling.", 2),
    ("The variety show welcomed multiple celebrity guests.", 2),
    ("Critics praised the movie’s soundtrack for its originality.", 2),
    ("The actor’s comeback role has stirred excitement among fans.", 2),
    ("A stand-up comedy tour is crossing the country this summer.", 2),
    ("A classic film festival celebrated golden-era cinema in a downtown theater.", 2),
    ("Comedy clubs reopened with stand-up specials, delighting local audiences.", 2),
    ("A famous magician performed death-defying stunts on a live broadcast.", 2),
    ("An up-and-coming musician released her debut album online.", 2),
    ("The streaming platform greenlit a series about historical explorers.", 2),
    ("A reality show invited fans to vote for the next pop idol.", 2),
    ("Folk music concerts gained a loyal following in small venues.", 2),
    ("A graffiti artist’s exhibit blurred the lines between street art and fine art.", 2),
    ("The improv troupe hosted workshops for aspiring comedians.", 2),
    ("A documentary exposed behind-the-scenes drama in the modeling industry.", 2),
    ("A best-selling fantasy novel is being adapted into a major film trilogy.", 2),
    ("Interactive theater experiences allowed the audience to shape the plot.", 2),
    ("Critics praised the new indie game for its emotional storytelling.", 2),
    ("A stand-up comedy competition found viral success on social media.", 2),
    ("Festival-goers camped out to see a legendary rock band’s final tour.", 2),
    ("A top DJ headlined an electronic music event spanning three days.", 2),
    ("An avant-garde dance troupe premiered an experimental performance piece.", 2),
    ("A new talk show format combined cooking segments with celebrity interviews.", 2),
    ("An upstart streaming service offered exclusive anime licenses.", 2),
    ("Musical theater workshops helped young performers develop their craft.", 2),
    ("A high-profile actor launched a podcast discussing mental health in Hollywood.", 2),
    ("The beloved children’s show introduced a diverse cast of puppet characters.", 2),
    ("Outdoor movie nights became a summer staple in various neighborhoods.", 2),
    ("An online singing contest discovered hidden talent from remote regions.", 2),
    ("A hip-hop producer collaborated with classical instrumentalists for a unique album.", 2),
    ("K-pop groups continued to dominate global charts with new releases.", 2),
    ("A retro arcade opened, featuring classic pinball and 8-bit games.", 2),
    ("The new stand-alone streaming platform focuses on niche horror films.", 2),
    ("A celebrity chef authored a memoir revealing behind-the-scenes kitchen drama.", 2),
    ("Video bloggers turned a road trip into a hit travel series.", 2),
    ("The Broadway revival of a beloved musical drew rave reviews.", 2),
    ("A talent competition turned a local singer into an overnight sensation.", 2),
    ("An unexpected cameo thrilled fans at a superhero movie premiere.", 2),
    ("Ballet aficionados attended a rare performance by an international star.", 2),
    ("A music label launched a scholarship for young producers and composers.", 2),
    ("The city hosted an outdoor comedy festival with acts from around the globe.", 2),
    ("A cable network rebranded to focus exclusively on sci-fi and fantasy shows.", 2),
    ("Fans lined up for a midnight launch of a cult-favorite series box set.", 2),
    ("Video-on-demand platforms offered classic sitcoms remastered in HD.", 2),
    ("A group of YouTubers filmed a paranormal investigation at a haunted mansion.", 2),

    # --------------------
    # TECHNOLOGY (label 3)
    # --------------------
    ("A robotics startup unveiled a household android for daily chores.", 3),
    ("Gamers praised the new console’s impressive graphics and speed.", 3),
    ("Researchers improved battery life by developing a novel nanomaterial.", 3),
    ("A hackathon attracted coders competing to solve social problems.", 3),
    ("Tech giants collaborated on a universal standard for wearables.", 3),
    ("A quantum computing demo showcased factorization of huge numbers.", 3),
    ("Engineers tested a prototype underwater drone for coral reef mapping.", 3),
    ("Green tech firms developed solar roads that power streetlights at night.", 3),
    ("Consumers eagerly awaited the foldable laptop’s official release.", 3),
    ("An open-source library promised faster AI model training on any GPU.", 3),
    ("Drone racing leagues gained popularity among younger audiences.", 3),
    ("A VR film festival let users immerse themselves in 360° narratives.", 3),
    ("Advances in 5G networking enabled seamless cloud gaming experiences.", 3),
    ("An e-ink device offered a paper-like reading experience for coders.", 3),
    ("Cybersecurity experts warned about next-gen phishing attacks.", 3),
    ("Digital twins of industrial plants reduced downtime and costs.", 3),
    ("A biotech startup used CRISPR to engineer pest-resistant crops.", 3),
    ("Crowdfunding helped a team build a giant robot for public demonstrations.", 3),
    ("Smart cities integrated sensors to manage traffic flow dynamically.", 3),
    ("AR glasses aimed to replace smartphones within the next decade.", 3),
    ("Tech conferences pivoted to virtual expos with interactive booths.", 3),
    ("A floating data center concept explored renewable ocean power.", 3),
    ("Holographic displays in cars promised safer driver assistance systems.", 3),
    ("A new Linux distro gained traction among privacy enthusiasts.", 3),
    ("Wearable health trackers moved toward continuous glucose monitoring.", 3),
    ("AI-assisted tutoring apps helped students with personalized learning plans.", 3),
    ("A hardware manufacturer launched biodegradable phone cases.", 3),
    ("Satellite internet providers competed for rural broadband markets.", 3),
    ("Blockchain-based identity systems aimed to curb identity theft.", 3),
    ("A 3D-printing startup produced custom prosthetics on demand.", 3),
    ("Haptic feedback devices made VR even more immersive for gamers.", 3),
    ("Gadget reviewers tested a phone with a built-in projector for presentations.", 3),
    ("A new smartphone brand promised monthly updates and open APIs.", 3),
    ("Edge computing frameworks minimized latency for real-time analytics.", 3),
    ("Developers open-sourced a deepfake detection toolkit.", 3),
    ("A major OS update introduced advanced voice recognition in multiple languages.", 3),
    ("Engineers tested solar-powered drones for package deliveries.", 3),
    ("Security cameras using facial recognition raised ethical debates.", 3),
    ("Medical VR simulations improved surgical training outcomes.", 3),
    ("Robotic arms folded laundry accurately in laboratory tests.", 3),
    ("A cutting-edge smartphone features a foldable display.", 3),
    ("Tech giants are racing to develop advanced AI models.", 3),
    ("A new software update promises better security and performance.", 3),
    ("The startup launched a delivery drone service in select cities.", 3),
    ("Cloud computing helps businesses scale their infrastructure.", 3),
    ("Engineers demonstrated a working prototype of a flying car.", 3),
    ("Many experts believe quantum computing will revolutionize data processing.", 3),
    ("Developers are embracing open-source software for faster innovation.", 3),
    ("A big data company unveiled a new analytics platform.", 3),
    ("Augmented reality headsets are gaining popularity for gaming.", 3),
    ("The self-driving car completed a cross-country journey autonomously.", 3),
    ("Security researchers discovered a vulnerability in popular routers.", 3),
    ("Robotics firms are partnering with manufacturers to automate tasks.", 3),
    ("A smartphone brand showcased its latest wireless charging pad.", 3),
    ("Smart home devices now integrate with multiple voice assistants.", 3),
    ("Virtual reality concerts are becoming more immersive for fans.", 3),
    ("Blockchain technology is transforming the way transactions are verified.", 3),
    ("A biotech firm is using AI to speed up medical research.", 3),
    ("The annual developer conference highlighted new coding tools.", 3),
    # --------------------
    # POLITICS (label 4)
    # --------------------
    ("A regional governor launched a clean-water initiative for rural towns.", 4),
    ("Embassies exchanged statements to defuse rising border tensions.", 4),
    ("Political parties scrambled to form a coalition after tight election results.", 4),
    ("The foreign minister delivered a speech on cross-border diplomacy.", 4),
    ("Constituents demanded transparency regarding new tax proposals.", 4),
    ("City council approved funding for public transportation improvements.", 4),
    ("Campaign volunteers knocked on doors to rally voter turnout.", 4),
    ("The supreme court ruled on a landmark case affecting healthcare access.", 4),
    ("Diplomats arranged a ceasefire in a long-standing regional conflict.", 4),
    ("A senator introduced a motion to regulate online political ads.", 4),
    ("An impassioned debate arose over environmental regulation rollbacks.", 4),
    ("A mayor’s controversial policy triggered protests in the downtown area.", 4),
    ("International observers monitored a major referendum for fairness.", 4),
    ("The parliament adjourned early due to a heated budget dispute.", 4),
    ("Ethics committees investigated alleged misuse of campaign funds.", 4),
    ("A newly formed minority party promised radical reforms in education.", 4),
    ("States convened a task force to address drought and resource allocation.", 4),
    ("A whistleblower came forward with allegations of lobbying misconduct.", 4),
    ("A former president endorsed a candidate for the upcoming primaries.", 4),
    ("Grassroots organizations pushed for ranked-choice voting nationwide.", 4),
    ("The defense minister announced changes to military recruitment policies.", 4),
    ("A policy summit invited experts to debate electoral system updates.", 4),
    ("The mayoral race tightened with three strong contenders emerging.", 4),
    ("Parliamentary committees disagreed on the timeline for new legislation.", 4),
    ("Government officials tested digital ID cards in a pilot program.", 4),
    ("Environmental activists met with lawmakers to propose green bills.", 4),
    ("An international treaty on cybersecurity threatened to stall over details.", 4),
    ("A local referendum granted more autonomy to a historically overlooked region.", 4),
    ("Budget cuts forced the closure of several public youth centers.", 4),
    ("The speaker of the house rejected calls for an immediate impeachment inquiry.", 4),
    ("Riots broke out after a delayed official election result announcement.", 4),
    ("New transparency laws required officials to disclose personal assets.", 4),
    ("The national assembly debated a motion on data privacy protections.", 4),
    ("Campaign rallies across the province drew record crowds this year.", 4),
    ("An education reform bill faced veto threats from the executive branch.", 4),
    ("A peace accord was celebrated as a major milestone in conflict resolution.", 4),
    ("Youth representation in politics improved with new leadership programs.", 4),
    ("A legislative session ended without passing key infrastructure bills.", 4),
    ("Observers praised the fair conduct of a complex multiparty election.", 4),
    ("A high-profile resignation shook the ruling party’s stability.", 4),
    ("The senator introduced a bill targeting tax reform.", 4),
    ("Election debates focused on healthcare and education funding.", 4),
    ("A local mayor announced a new environmental initiative.", 4),
    ("Political parties rallied supporters ahead of the vote.", 4),
    ("Diplomatic relations improved after the summit between the two nations.", 4),
    ("The president signed an executive order addressing climate change.", 4),
    ("Protesters marched outside the capitol demanding policy changes.", 4),
    ("Polls indicate a tight race between leading candidates.", 4),
    ("Legislators reached a bipartisan agreement on infrastructure spending.", 4),
    ("A governor declared a state of emergency due to severe storms.", 4),
    ("A political scandal led to multiple resignations in the cabinet.", 4),
    ("Campaign finance reform remains a controversial topic.", 4),
    ("The prime minister reshuffled the cabinet to tackle new challenges.", 4),
    ("An international treaty on trade was renegotiated this week.", 4),
    ("Voters demanded greater transparency from their representatives.", 4),
    ("A senator's filibuster delayed a critical piece of legislation.", 4),
    ("Observers questioned the ethics of lobbying practices on the hill.", 4),
    ("Officials from multiple countries met for a global policy conference.", 4),
    ("A sudden resignation triggered a by-election in the district.", 4),
    ("Activists urged lawmakers to pass a civil rights bill.", 4),
]
    # -------------------------------------------------------
# 300 LINES FOR classification_data
# (Categories: 0=Sports, 1=Business, 2=Entertainment, 3=Technology, 4=Politics)
# -------------------------------------------------------


sentiment_data = [
    # --------------------
    # NEGATIVE (now 0)
    # --------------------
    ("They forgot my birthday and didn’t even apologize later.", 0),
    ("The cafe’s coffee tasted burnt and bitter all morning.", 0),
    ("Our conference call dropped four times, completely wasting our time.", 0),
    ("He mocks everyone’s suggestions without offering any of his own.", 0),
    ("The event was poorly advertised, so hardly anyone showed up.", 0),
    ("I tried to return the defective item, but the process was a nightmare.", 0),
    ("Her dismissive reply made me regret asking for help.", 0),
    ("We found cockroaches in the cabin, which ruined our vacation.", 0),
    ("I can’t stand the constant construction noise at dawn.", 0),
    ("Their automated system kept me on hold for nearly an hour.", 0),
    ("The hotel lost my reservation and gave me the smallest room available.", 0),
    ("My salad arrived wilted, and the dressing tasted off.", 0),
    ("He rudely interrupted every speaker during the seminar.", 0),
    ("The road closures caused massive traffic jams with no detours provided.", 0),
    ("Their new policy just complicates everything more than it helps.", 0),
    ("I received a faulty upgrade that crashed my system immediately.", 0),
    ("She constantly criticizes minor details, driving everyone away.", 0),
    ("The store manager showed zero empathy for my complaint.", 0),
    ("A glitch wiped my saved game progress, and there’s no backup.", 0),
    ("Our neighbors’ dog howls all night, and we can’t sleep.", 0),
    ("He belittled my effort in front of the entire team.", 0),
    ("They used bait-and-switch tactics in their advertisement.", 0),
    ("His harsh teaching style demotivated the entire class.", 0),
    ("Customer support didn’t respond to my emails for weeks.", 0),
    ("The chat service disconnected mid-conversation, wasting my time.", 0),
    ("I tried the diet plan, but it gave me zero results and lots of stress.", 0),
    ("They promised a full refund but only returned a fraction of my money.", 0),
    ("Our dinner arrived cold, and they refused to remake it.", 0),
    ("He accused me of lying before hearing the full story.", 0),
    ("The software’s frequent crashes led me to abandon the product completely.", 0),
    ("They served stale bread, and the waiter ignored our complaints.", 0),
    ("The museum exhibit was overpriced and underwhelming.", 0),
    ("She spread rumors that caused undue drama and conflict.", 0),
    ("After standing in line for hours, they told me they ran out of tickets.", 0),
    ("The job interview felt more like an interrogation than a conversation.", 0),
    ("A data breach exposed sensitive info, and the company barely apologized.", 0),
    ("He spoke in a patronizing tone throughout the entire meeting.", 0),
    ("We received a damaged shipment twice in a row.", 0),
    ("Their last-minute cancellations threw off my entire schedule.", 0),
    ("His loud, condescending laughter made everyone uncomfortable.", 0),
    ("I had high hopes for this service, but it’s been nothing but trouble.", 0),
    ("They blocked my account without a clear explanation.", 0),
    ("The park’s renovations removed benches and shade, making it unbearable.", 0),
    ("She left me stranded when we were supposed to carpool.", 0),
    ("They overbooked the flight, and I was bumped to the next day.", 0),
    ("His phone calls are always negative rants with no solution in sight.", 0),
    ("The new update broke key features, making the app unusable.", 0),
    ("I found mold in the bathroom, and management didn’t fix it for days.", 0),
    ("They played loud music in the office, disrupting everyone’s work.", 0),
    ("He refused to sign the documents after months of negotiation.", 0),
    ("The candle’s scent was nauseating, not calming as advertised.", 0),
    ("Despite the brand’s hype, the shoes fell apart after a week.", 0),
    ("She constantly brags and demeans others in the process.", 0),
    ("Unreliable Wi-Fi made remote work a constant struggle.", 0),
    ("Their newsletter spam continues, even though I unsubscribed twice.", 0),
    ("The buffet ran out of food, and no one replenished it.", 0),
    ("My coworker keeps taking credit for my ideas.", 0),
    ("The rep gave vague answers, leaving my issues unresolved.", 0),
    ("He stormed into the meeting, yelled at everyone, and then left.", 0),
    ("The power outage lasted for hours, spoiling all our groceries.", 0),
    ("Her constant negative remarks drain the entire team’s enthusiasm.", 0),
    ("They delivered half the materials, leaving the project incomplete.", 0),
    ("The property manager ignored our complaints about mold for months.", 0),
    ("Their marketing made false claims that led to disappointment.", 0),
    ("He insulted my cooking in front of guests, which was humiliating.", 0),
    ("The slow loading times made the website nearly impossible to use.", 0),
    ("They claimed free shipping but tacked on hidden fees later.", 0),
    ("His grumpy demeanor put everyone on edge during the trip.", 0),
    ("Every video from that platform buffers endlessly.", 0),
    ("They lost my appointment, and I had to reschedule two weeks later.", 0),
    ("Her constant nagging overshadowed any attempt at conversation.", 0),
    ("He refused to fix the error and blamed me for his mistake.", 0),
    ("The flight was delayed seven hours with no proper explanation.", 0),
    ("The marinade tasted sour, and the meat was undercooked.", 0),
    ("Their premium plan offered nothing better than the basic tier.", 0),
    ("She spread negativity among the group, causing frequent arguments.", 0),
    ("I was promised a quiet room, but it overlooked a noisy highway.", 0),
    ("The video quality was grainy, making it hard to watch the documentary.", 0),
    ("He openly criticized my progress instead of offering help.", 0),
    ("The used car broke down less than a week after purchase.", 0),
    ("They keep ignoring my service requests, leaving it broken.", 0),
    ("He’s always late but never apologizes or explains why.", 0),
    ("The house party was chaotic, with no consideration for neighbors.", 0),
    ("I found nails in my tire after parking in their messy lot.", 0),
    ("They sold my personal data to advertisers without consent.", 0),
    ("She canceled plans last minute, wasting my non-refundable tickets.", 0),
    ("The store’s layout is so confusing, I can never find what I need.", 0),
    ("He complains about everything, bringing down everyone’s mood.", 0),
    ("Their mandatory meeting was just an hour of pointless lecturing.", 0),
    ("She demanded extra work from me but took the credit herself.", 0),
    ("The station’s announcements were unclear, causing me to miss my train.", 0),
    ("They store confidential documents carelessly, risking privacy breaches.", 0),
    ("His bleak outlook on life ends every chat in despair.", 0),
    ("They sold out of the only item I needed and offered no alternative.", 0),
    ("My doctor’s office overbooked, making me wait two hours for a 5-minute exam.", 0),
    ("He snapped at me over a minor misunderstanding, which felt harsh.", 0),
    ("The fancy dessert looked good but tasted stale.", 0),
    ("They rescheduled the meeting three times, messing up my entire day.", 0),
    ("No one from management shows concern for employee well-being here.", 0),

    # --------------------
    # NEUTRAL (now 1)
    # --------------------
    ("I drove past the library but didn’t have time to stop.", 1),
    ("She placed the groceries on the counter and walked away.", 1),
    ("He returned the pen after borrowing it for the meeting.", 1),
    ("We watched the newscast silently, then turned off the TV.", 1),
    ("They sorted the mail into separate piles for each roommate.", 1),
    ("The courier delivered the package on Thursday, as expected.", 1),
    ("She usually walks to work unless the weather is bad.", 1),
    ("A coworker mentioned the staff meeting schedule, and I noted it.", 1),
    ("He switched to a different brand of toothpaste, noticing no difference.", 1),
    ("The server brought extra napkins when asked, then left.", 1),
    ("They installed security cameras in the lobby last week.", 1),
    ("I rechecked the receipt to ensure the total was correct.", 1),
    ("The bus arrived exactly on time; I boarded without issue.", 1),
    ("She folded the laundry while humming quietly.", 1),
    ("He scanned the QR code on the flyer out of curiosity.", 1),
    ("I made a backup of the files just in case.", 1),
    ("The lunch menu changed slightly, but nothing remarkable.", 1),
    ("They tested the microphone once, then started the presentation.", 1),
    ("He wrote down a reminder to buy more milk and bread.", 1),
    ("We listened to a podcast but didn’t finish it.", 1),
    ("She canceled the free trial before any charges applied.", 1),
    ("He requested a copy of the report, then returned to his desk.", 1),
    ("The roads were mostly clear except for a bit of construction.", 1),
    ("She completed her chores as usual, no complaints raised.", 1),
    ("I noticed the neighbors got a new fence, but I didn’t ask about it.", 1),
    ("They tested the fire alarm, and it worked as it should.", 1),
    ("He finished reading the manual, then put it away.", 1),
    ("The meeting ended with a simple handshake, nothing more.", 1),
    ("She wiped the counters after cooking, leaving the kitchen tidy.", 1),
    ("I studied the map briefly to confirm the route.", 1),
    ("They concluded the call without scheduling a follow-up.", 1),
    ("He sat in the waiting room, reading a magazine quietly.", 1),
    ("She replaced the old batteries in the TV remote.", 1),
    ("I placed the jacket on the rack and went into the living room.", 1),
    ("They posted a note on the fridge about the new cleaning schedule.", 1),
    ("He watched a tutorial online but didn’t attempt the project yet.", 1),
    ("She answered a few customer emails, then took a short break.", 1),
    ("The campus library extended its hours by an hour, no further changes.", 1),
    ("He paid the utility bill online and saved the confirmation.", 1),
    ("We briefly discussed the forecast for next week, then changed topics.", 1),
    ("She organized her desk drawers, discarding old receipts.", 1),
    ("They taped a flyer to the bulletin board in the hallway.", 1),
    ("He put the leftover pasta in a container for tomorrow’s lunch.", 1),
    ("I noticed the office printer was low on ink but still functional.", 1),
    ("She commented on the traffic, stating it was typical for a weekday.", 1),
    ("He locked the workshop and turned off the lights before leaving.", 1),
    ("They scrolled through social media without reacting to any posts.", 1),
    ("I checked the sale prices but decided not to buy anything.", 1),
    ("She answered the phone politely, then handed it to her manager.", 1),
    ("He walked into the grocery store, grabbed a basket, and started shopping.", 1),
    ("We parted ways after the meeting, each heading home separately.", 1),
    ("She emailed the document to her colleague and waited for feedback.", 1),
    ("He tested the speakers briefly to confirm they were functional.", 1),
    ("They consolidated files into one folder for easier access.", 1),
    ("I listened to the radio news but didn’t pay much attention.", 1),
    ("She placed the shipping label on the box and scheduled a pickup.", 1),
    ("He updated the website’s contact info after verifying it.", 1),
    ("They observed the presentation quietly, offering no comments.", 1),
    ("I took a short walk during lunch, then returned to my desk.", 1),
    ("She turned on the fan because the room felt slightly warm.", 1),
    ("He wrapped the gift in plain paper with no decoration.", 1),
    ("They ended the video call once all tasks were assigned.", 1),
    ("I moved the chair to the corner, thinking it looked better there.", 1),
    ("She rinsed the dishes and left them on the rack to dry.", 1),
    ("He scanned the QR code on the ticket to check authenticity.", 1),
    ("We quickly reviewed the notes from the meeting and archived them.", 1),
    ("She checked the car’s mileage but didn’t mention anything else.", 1),
    ("He confirmed the dentist appointment via text message.", 1),
    ("They replaced the default ringtone on their phone with another default tone.", 1),
    ("I rearranged the books on my shelf to group similar topics.", 1),
    ("She scrolled through the policy documents, then closed them.", 1),
    ("He unsubscribed from a newsletter he rarely read.", 1),
    ("They performed routine maintenance on the office printer without issue.", 1),
    ("I kept the receipt for a future expense report, just in case.", 1),
    ("She deleted old emails to tidy her inbox, not saving any attachments.", 1),
    ("He sampled a new snack brand but didn’t have a strong opinion on it.", 1),
    ("The library closed at its usual time, no special announcements given.", 1),
    ("They posted a standard update about their hours on social media.", 1),
    ("I adjusted the thermostat by a single degree, not expecting much difference.", 1),
    ("She locked the front door behind her, then headed to the store.", 1),
    ("He watched a documentary on manufacturing processes, found it okay.", 1),
    ("They placed an online order for groceries, no special items included.", 1),
    ("I noticed the mild weather outside but stayed indoors anyway.", 1),
    ("She handed out name tags at the event, then took a seat.", 1),
    ("He wrote down tomorrow’s to-do list before clocking out.", 1),
    ("They moved a potted plant closer to the window for better light.", 1),
    ("I followed the recipe exactly, resulting in a basic meal.", 1),
    ("She got a parking spot near the entrance by pure chance.", 1),
    ("He read a magazine article in the waiting area, then tossed it.", 1),
    ("They ended the day as they started—without anything notable happening.", 1),

    # --------------------
    # POSITIVE (now 2)
    # --------------------
    ("My new ergonomic keyboard has greatly improved my typing comfort.", 2),
    ("They sent me a thoughtful care package during my recovery.", 2),
    ("I got front-row seats to my favorite band’s concert; it was incredible.", 2),
    ("Her supportive feedback helped me refine my project successfully.", 2),
    ("We had a spontaneous game night that lifted everyone’s spirits.", 2),
    ("He regained confidence after acing his final exam.", 2),
    ("She discovered a new hobby that brings her daily joy.", 2),
    ("The free upgrade to a suite made our weekend getaway even better.", 2),
    ("I happily found a coupon that saved me a decent amount at checkout.", 2),
    ("They organized a heartfelt farewell party for a retiring colleague.", 2),
    ("Our team completed the complex assignment ahead of schedule.", 2),
    ("He kindly offered me a ride home when my car broke down.", 2),
    ("Her new painting brightened up the entire living room.", 2),
    ("I feel great about adopting a puppy; it’s been a wonderful addition.", 2),
    ("Their charity auction raised more funds than expected for local shelters.", 2),
    ("We enjoyed a perfectly clear night sky for stargazing.", 2),
    ("She boosted my confidence with encouraging words before my interview.", 2),
    ("He received a surprise bonus for his exceptional performance.", 2),
    ("The bookstore’s cozy reading nook made me stay longer than planned.", 2),
    ("I loved catching up with old friends, laughing at shared memories.", 2),
    ("They turned the dull office space into a vibrant workspace.", 2),
    ("She took the initiative to plan a team-building lunch that everyone enjoyed.", 2),
    ("We celebrated my promotion with a small gathering of close friends.", 2),
    ("He found an amazing deal on a laptop that exceeded his specs needs.", 2),
    ("She discovered a hidden talent for playing the ukulele.", 2),
    ("I appreciate how these new shoes feel both stylish and comfortable.", 2),
    ("They managed to fix the glitch quickly, restoring my faith in tech support.", 2),
    ("His mentor’s advice propelled him to new career heights.", 2),
    ("We spontaneously sang karaoke, and it was an absolute blast.", 2),
    ("She got accepted into her dream university program.", 2),
    ("The renovation unveiled charming original features in our old house.", 2),
    ("He took up cooking and wowed everyone with a gourmet meal.", 2),
    ("A random act of kindness from a stranger made my entire day.", 2),
    ("They offered me a flexible schedule, improving my work-life balance.", 2),
    ("Her stand-up comedy routine won over even the toughest critics.", 2),
    ("I successfully launched my small business website without glitches.", 2),
    ("Our road trip revealed stunning landscapes at every turn.", 2),
    ("He resolved the conflict calmly, leaving everyone relieved.", 2),
    ("She discovered a local cafe with the best pastries in town.", 2),
    ("I love the crisp air during my morning jog; it energizes me.", 2),
    ("They turned an abandoned lot into a community garden, which is lovely.", 2),
    ("He found a lost puppy and reunited it with its owner.", 2),
    ("We turned a simple backyard into a wonderful picnic spot.", 2),
    ("Her philanthropic efforts earned recognition from local media.", 2),
    ("I learned to meditate, and it has significantly reduced my stress.", 2),
    ("He chipped in to help me finish the project, saving me hours of work.", 2),
    ("They gifted me a handmade card that felt incredibly personal.", 2),
    ("The festival had lively music and delicious food, a perfect combo.", 2),
    ("She overcame her fear of public speaking and received applause.", 2),
    ("A random compliment from a coworker boosted my entire week.", 2),
    ("His creative solution solved the issue in record time.", 2),
    ("We baked cookies together, filling the house with a delightful aroma.", 2),
    ("She found a lost earring in the park and returned it to its owner.", 2),
    ("I discovered an uplifting podcast that brightens my morning commute.", 2),
    ("He introduced me to a new workout routine that feels rewarding.", 2),
    ("Their heartfelt tribute moved everyone to happy tears.", 2),
    ("I successfully ran my first 5K race, feeling accomplished.", 2),
    ("We turned a boring weekend into a spontaneous road adventure.", 2),
    ("She received heartfelt feedback on her short story, fueling her creativity.", 2),
    ("I saved enough money for a fun vacation next month.", 2),
    ("They threw a small but meaningful surprise party for my birthday.", 2),
    ("His calm guidance got us through a stressful situation unscathed.", 2),
    ("I stumbled upon an old photo album that brought back cherished memories.", 2),
    ("She discovered a painting class that reignited her passion for art.", 2),
    ("They volunteered at an animal shelter and felt truly fulfilled.", 2),
    ("His perseverance paid off, landing him a spot in the local orchestra.", 2),
    ("We found an ideal picnic spot by the river with plenty of shade.", 2),
    ("Her heartfelt letter brought comfort during a challenging time.", 2),
    ("I aced my final presentation and got positive feedback from the professor.", 2),
    ("They minted a new token of appreciation for loyal customers, how thoughtful!", 2),
    ("He found a missing piece of family history, reuniting old relatives.", 2),
    ("We tested a new board game that turned out to be incredibly fun.", 2),
    ("She turned her passion for baking into a thriving side business.", 2),
    ("I discovered a new path at the park that offers a tranquil walk.", 2),
    ("They launched a fundraiser that exceeded all donation goals.", 2),
    ("He overcame his fear of heights by successfully zip-lining.", 2),
    ("Her performance in the play captured everyone’s heart.", 2),
    ("We danced to our favorite songs and forgot all our worries.", 2),
    ("He woke up early to watch the sunrise, feeling at peace.", 2),
    ("They transformed the dull basement into a cozy entertainment room.", 2),
    ("I bumped into an old friend and had a wonderful catch-up session.", 2),
    ("She set up a mini-library on her porch, and neighbors love it.", 2),
    ("He crafted handmade gifts for his entire family, making them smile.", 2),
    ("We raised a toast to our successful year and future endeavors.", 2),
    ("Her volunteer work in the senior center lifted many spirits.", 2),
    ("I learned a new language skill that boosted my confidence immensely.", 2),
    ("They rehabilitated an injured bird and safely released it later.", 2),
    ("He found a solution to a long-standing issue at work, earning praise.", 2),
    ("I reunited with my cousin after years, and we reconnected seamlessly.", 2),
    ("She overcame self-doubt and published her first article to great acclaim.", 2),
    ("They created a group chat that fosters supportive daily check-ins.", 2),
    ("He repainted the living room in bright colors that cheer everyone up.", 2),
]


# sentiment_data: 300 total lines
# -1 = negative (100 lines)
#  0 = neutral  (100 lines)
#  1 = positive (100 lines)



# import this data in train.py
